device: /dev/gps
frame_id: gps
uart1:
  baudrate: 115200
config_on_startup: true
rate: 30
nav_rate: 1                  # [# of measurement cycles], recommended 1 Hz, may
dgnss_mode: 3                # Fixed mode
tmode3: 0
